// ISO 3166-1 alpha-2 code + common name, UN member states + widely recognized (~195)
const COUNTRIES = [
["af","Afghanistan"],["al","Albania"],["dz","Algeria"],["ad","Andorra"],["ao","Angola"],
["ag","Antigua and Barbuda"],["ar","Argentina"],["am","Armenia"],["au","Australia"],["at","Austria"],
["az","Azerbaijan"],["bs","Bahamas"],["bh","Bahrain"],["bd","Bangladesh"],["bb","Barbados"],
["by","Belarus"],["be","Belgium"],["bz","Belize"],["bj","Benin"],["bt","Bhutan"],
["bo","Bolivia"],["ba","Bosnia and Herzegovina"],["bw","Botswana"],["br","Brazil"],["bn","Brunei"],
["bg","Bulgaria"],["bf","Burkina Faso"],["bi","Burundi"],["cv","Cabo Verde"],["kh","Cambodia"],
["cm","Cameroon"],["ca","Canada"],["cf","Central African Republic"],["td","Chad"],["cl","Chile"],
["cn","China"],["co","Colombia"],["km","Comoros"],["cg","Republic of the Congo"],["cd","DR Congo"],
["cr","Costa Rica"],["ci","Cote d'Ivoire"],["hr","Croatia"],["cu","Cuba"],["cy","Cyprus"],
["cz","Czechia"],["dk","Denmark"],["dj","Djibouti"],["dm","Dominica"],["do","Dominican Republic"],
["ec","Ecuador"],["eg","Egypt"],["sv","El Salvador"],["gq","Equatorial Guinea"],["er","Eritrea"],
["ee","Estonia"],["sz","Eswatini"],["et","Ethiopia"],["fj","Fiji"],["fi","Finland"],
["fr","France"],["ga","Gabon"],["gm","Gambia"],["ge","Georgia"],["de","Germany"],
["gh","Ghana"],["gr","Greece"],["gd","Grenada"],["gt","Guatemala"],["gn","Guinea"],
["gw","Guinea-Bissau"],["gy","Guyana"],["ht","Haiti"],["hn","Honduras"],["hu","Hungary"],
["is","Iceland"],["in","India"],["id","Indonesia"],["ir","Iran"],["iq","Iraq"],
["ie","Ireland"],["il","Israel"],["it","Italy"],["jm","Jamaica"],["jp","Japan"],
["jo","Jordan"],["kz","Kazakhstan"],["ke","Kenya"],["ki","Kiribati"],["kp","North Korea"],
["kr","South Korea"],["xk","Kosovo"],["kw","Kuwait"],["kg","Kyrgyzstan"],["la","Laos"],
["lv","Latvia"],["lb","Lebanon"],["ls","Lesotho"],["lr","Liberia"],["ly","Libya"],
["li","Liechtenstein"],["lt","Lithuania"],["lu","Luxembourg"],["mg","Madagascar"],["mw","Malawi"],
["my","Malaysia"],["mv","Maldives"],["ml","Mali"],["mt","Malta"],["mh","Marshall Islands"],
["mr","Mauritania"],["mu","Mauritius"],["mx","Mexico"],["fm","Micronesia"],["md","Moldova"],
["mc","Monaco"],["mn","Mongolia"],["me","Montenegro"],["ma","Morocco"],["mz","Mozambique"],
["mm","Myanmar"],["na","Namibia"],["nr","Nauru"],["np","Nepal"],["nl","Netherlands"],
["nz","New Zealand"],["ni","Nicaragua"],["ne","Niger"],["ng","Nigeria"],["mk","North Macedonia"],
["no","Norway"],["om","Oman"],["pk","Pakistan"],["pw","Palau"],["pa","Panama"],
["pg","Papua New Guinea"],["py","Paraguay"],["pe","Peru"],["ph","Philippines"],["pl","Poland"],
["pt","Portugal"],["qa","Qatar"],["ro","Romania"],["ru","Russia"],["rw","Rwanda"],
["kn","Saint Kitts and Nevis"],["lc","Saint Lucia"],["vc","Saint Vincent and the Grenadines"],["ws","Samoa"],["sm","San Marino"],
["st","Sao Tome and Principe"],["sa","Saudi Arabia"],["sn","Senegal"],["rs","Serbia"],["sc","Seychelles"],
["sl","Sierra Leone"],["sg","Singapore"],["sk","Slovakia"],["si","Slovenia"],["sb","Solomon Islands"],
["so","Somalia"],["za","South Africa"],["ss","South Sudan"],["es","Spain"],["lk","Sri Lanka"],
["sd","Sudan"],["sr","Suriname"],["se","Sweden"],["ch","Switzerland"],["sy","Syria"],
["tw","Taiwan"],["tj","Tajikistan"],["tz","Tanzania"],["th","Thailand"],["tl","Timor-Leste"],
["tg","Togo"],["to","Tonga"],["tt","Trinidad and Tobago"],["tn","Tunisia"],["tr","Turkey"],
["tm","Turkmenistan"],["tv","Tuvalu"],["ug","Uganda"],["ua","Ukraine"],["ae","United Arab Emirates"],
["gb","United Kingdom"],["us","United States"],["uy","Uruguay"],["uz","Uzbekistan"],["vu","Vanuatu"],
["va","Vatican City"],["ve","Venezuela"],["vn","Vietnam"],["ye","Yemen"],["zm","Zambia"],
["zw","Zimbabwe"]
];

const REGIONS = {
af:"Asia",al:"Europe",dz:"Africa",ad:"Europe",ao:"Africa",ag:"North America",
ar:"South America",am:"Asia",au:"Oceania",at:"Europe",az:"Asia / Europe",bs:"North America",
bh:"Asia",bd:"Asia",bb:"North America",by:"Europe",be:"Europe",bz:"North America",
bj:"Africa",bt:"Asia",bo:"South America",ba:"Europe",bw:"Africa",br:"South America",
bn:"Asia",bg:"Europe",bf:"Africa",bi:"Africa",cv:"Africa",kh:"Asia",
cm:"Africa",ca:"North America",cf:"Africa",td:"Africa",cl:"South America",cn:"Asia",
co:"South America",km:"Africa",cg:"Africa",cd:"Africa",cr:"North America",ci:"Africa",
hr:"Europe",cu:"North America",cy:"Asia / Europe",cz:"Europe",dk:"Europe",dj:"Africa",
dm:"North America",do:"North America",ec:"South America",eg:"Africa / Asia",sv:"North America",gq:"Africa",
er:"Africa",ee:"Europe",sz:"Africa",et:"Africa",fj:"Oceania",fi:"Europe",
fr:"Europe",ga:"Africa",gm:"Africa",ge:"Asia / Europe",de:"Europe",gh:"Africa",
gr:"Europe",gd:"North America",gt:"North America",gn:"Africa",gw:"Africa",gy:"South America",
ht:"North America",hn:"North America",hu:"Europe",is:"Europe",in:"Asia",id:"Asia",
ir:"Asia",iq:"Asia",ie:"Europe",il:"Asia",it:"Europe",jm:"North America",
jp:"Asia",jo:"Asia",kz:"Asia / Europe",ke:"Africa",ki:"Oceania",kp:"Asia",
kr:"Asia",xk:"Europe",kw:"Asia",kg:"Asia",la:"Asia",lv:"Europe",
lb:"Asia",ls:"Africa",lr:"Africa",ly:"Africa",li:"Europe",lt:"Europe",
lu:"Europe",mg:"Africa",mw:"Africa",my:"Asia",mv:"Asia",ml:"Africa",
mt:"Europe",mh:"Oceania",mr:"Africa",mu:"Africa",mx:"North America",fm:"Oceania",
md:"Europe",mc:"Europe",mn:"Asia",me:"Europe",ma:"Africa",mz:"Africa",
mm:"Asia",na:"Africa",nr:"Oceania",np:"Asia",nl:"Europe",nz:"Oceania",
ni:"North America",ne:"Africa",ng:"Africa",mk:"Europe",no:"Europe",om:"Asia",
pk:"Asia",pw:"Oceania",pa:"North America",pg:"Oceania",py:"South America",pe:"South America",
ph:"Asia",pl:"Europe",pt:"Europe",qa:"Asia",ro:"Europe",ru:"Europe / Asia",
rw:"Africa",kn:"North America",lc:"North America",vc:"North America",ws:"Oceania",sm:"Europe",
st:"Africa",sa:"Asia",sn:"Africa",rs:"Europe",sc:"Africa",sl:"Africa",
sg:"Asia",sk:"Europe",si:"Europe",sb:"Oceania",so:"Africa",za:"Africa",
ss:"Africa",es:"Europe",lk:"Asia",sd:"Africa",sr:"South America",se:"Europe",
ch:"Europe",sy:"Asia",tw:"Asia",tj:"Asia",tz:"Africa",th:"Asia",
tl:"Asia",tg:"Africa",to:"Oceania",tt:"North America",tn:"Africa",tr:"Asia / Europe",
tm:"Asia",tv:"Oceania",ug:"Africa",ua:"Europe",ae:"Asia",gb:"Europe",
us:"North America",uy:"South America",uz:"Asia",vu:"Oceania",va:"Europe",ve:"South America",
vn:"Asia",ye:"Asia",zm:"Africa",zw:"Africa",
};
